### ISSUE TITLE
In Scintillua 5.3 and Scite 5.2.2 it won't work.

### ISSUE THREAD

**Issue by telppa** [Lexikos/Scintillua-ahk#1]
I used scite4ahk so many years.

I've [made many improvements](https://github.com/telppa/SciTE4AutoHotkey-Plus) to scite4ahk since fincs stopped being updated.

For many reasons, I only let it propagate among Chinese users.

About two years ago, I learned about Scintillua-ahk and used it successfully on scite4ahk.

I knew that it was a great opportunity to create a new scite4ahk.

Over the past two years, I've learned a lot about how to interact with scite, and i thought  it's time to create a new scite4ahk!
But unfortunately Scintillua-ahk doesn't work on the latest version(Scintillua 5.3 and Scite 5.2.2).
I tried a lot of things, but it still didn't work.

Can you fix this issue?

As long as Scintillua can run, I can keep learning lua or other things and use them to improve the new scite4ahk.

**Comment by telppa** [comment]
here is a minimum zip package for test.
[scite(minimum for test).zip](https://github.com/Lexikos/Scintillua-ahk/files/8578794/scite.minimum.for.test.zip)

**Comment by mark-wiemer** [comment]
I'm also having this issue. @Lexikos , have you been able to get this project working with SciTE4AutoHotkey v3.1.0?

**Comment by Lexikos** [comment]
I don't remember what stopped me, the last time I looked at updating this. Probably lack of motivation to update the base version of SciTE. I was using SciTE v3.0.6.1 until recently - I think that was even older than fincs' last release before his recent return.

I will try to make some time to look into this soon.

**Comment by Lexikos** [comment]
Well, apparently the only thing stopping it was the use of `io` at the very start of the lexers, which I had used to facilitate debugging with `print`. I can't see anything in the Scintillua changelog or documentation mentioning it, but apparently now `io` is undefined. Commit b9ae79f is working for me with standard SciTE 5.2.3 and SciTE4AutoHotkey 3.1.00 (SciTE 5.2.2).

I merely added this to SciTEUser.properties to enable it:
```properties
import C:\Projects\temp\Scintillua\lexers\lpeg
lexilla.context.lpeg.home=C:\Projects\temp\Scintillua\lexers
file.patterns.ahk=*.ahk
lexer.$(file.patterns.ahk)=lpeg.ahk1
```
Obviously change the path. I used an absolute path because I was having trouble getting it working, which was just because I was putting the lexers folder in the wrong folder (SciteDefaultHome != SciteUserHome).

`file.patterns.ahk=*.ahk` is redundant for SciTE4AutoHotkey.

The standard ways to do some things in Scintillua appears to have changed, but apparently the compatibility with the old ways has been kept... just not `io`.

**Comment by mark-wiemer** [comment]
I haven't gotten this working quite yet. @Lexikos, am I missing something?

1. Uninstalled everything related to Scintilla, SciTE, SciTE4AutoHotkey, Scintillua, and Scintillua-ahk.
1. Reinstalled [fincs/SciTE4AutoHotkey/releases/tag/v3.1.0](https://github.com/fincs/SciTE4AutoHotkey/releases/tag/v3.1.0)
   ✅ At this point, syntax highlighting is working fine.
      <details><summary>Screenshot</summary>
      
      ![screenshot of correctly highlighted text](https://user-images.githubusercontent.com/7833360/177011998-df737cf5-2cfe-4059-a408-21621a830bac.png)

      </details>

1. Read [Lexikos/scintillua-ahk](https://github.com/Lexikos/Scintillua-ahk#installation)
1. Downloaded [Scintillua 5.3 (latest version)](https://github.com/orbitalquark/scintillua/releases/tag/scintillua_5.3)
1. Moved `lexers` into my home directory. 
   ✅ Syntax highlighting still working fine.
1. Downloaded and copied all files (except `readme.md`) from `scintillua-ahk` into `lexers`, overriding `lexer.lua`. This was from commit https://github.com/Lexikos/Scintillua-ahk/commit/b9ae79f3a1a2ef93e43391a9d9a5a53b7ccb6302
   ✅ Syntax highlighting still working fine.
1. Added `import lexers/lpeg_s4a` to end of `SciTEUser.properties`
   ❌ Broke as soon as I saved. Fixes itself once I remove the line and save. This is expected, I think.
1. Added `dofile(props['SciteUserHome']..'/lexers/lpeg_s4a.lua')` to `UserLuaScript.lua`
   ❌ Broken
1. Read https://github.com/Lexikos/Scintillua-ahk/issues/1
1. Updated custom settings to the following:

   ```
   import lexers/lpeg_s4a
   import lexers/lpeg
   lexilla.context.lpeg.home=lexers
   file.patterns.ahk=*.ahk
   lexer.$(file.patterns.ahk)=lpeg.ahk1
   ```

1. Restart SciTE4AutoHotkey
   ❌😞 still broken

Folder structure
- SciTE
  - lexers
    - lexer.lua (overwritten)
    - lpeg.properties
    - lpeg_s4a.properties
    - ...many other files...
  - UserLuaScript.lua
  - SciTEUser.properties
  - ...many other files...

**Comment by mark-wiemer** [comment]
If I use an absolute path on Windows, do I need to use backslashes? What if the folder name contains a space, is that a special case? e.g. `C:\Program Files\SciTE\lexers`

**Comment by mark-wiemer** [comment]
Oh! I see now on https://orbitalquark.github.io/scintillua/ that "Scintillua requires Scintilla 5.0.1 or greater and [Lexilla](https://www.scintilla.org/Lexilla.html) 5.1.0 or greater for a drop-in installation.", silly me. Let me make sure I have that installed.

**Comment by mark-wiemer** [comment]
:( Lexilla comes with SciTE which comes with SciTE4AutoHotkey, I think :( I'm not able to get this working with either SciTE or SciTE4AutoHotkey. Help would be much appreciated if anyone else has figured this out :/

**Comment by Lexikos** [comment]
Commit b9ae79f3 only fixes the lexer itself (ahk1.lua or ahk2.lua) to work with Scintillua 5.3 and SciTE 5.2.2. Note:
> I merely added this to SciTEUser.properties to enable it:
> ```
> import C:\Projects\temp\Scintillua\lexers\lpeg
> lexilla.context.lpeg.home=C:\Projects\temp\Scintillua\lexers
> file.patterns.ahk=*.ahk
> lexer.$(file.patterns.ahk)=lpeg.ahk1
> ```
... and compare to the content of lpeg_s4a.properties in the same commit:
```
lexer.lpeg.home=$(SciteUserHome)/lexers
```
I updated this property and some other things the next day. (I don't monitor GitHub notifications and didn't think to comment here afterward.)
